### ISSUE TITLE
Create Google Maps API functionality

### ISSUE THREAD

**Issue by jacksonmaltby** [jacksonmaltby/where-wolf#5]

**Comment by Goobber33** [comment]
Created Google Maps API, followed the documentation to add the map with a marker to the website. I sized the map a bit on the webpage, but it will need to be adjusted using tailwinds css or normal css, which I believe Erin is working on.

**Comment by Goobber33** [comment]
Wrote out a function that will take Yelp API and use the search button to list out businesses, and show on google maps where the businesses are located. Waiting on the Yelp Fusion API key

**Comment by Goobber33** [comment]
We moved away from Google Maps API as we were running into issues implementing it, and we wouldn't finish this project in a timely manner. I removed all google maps functions and added Leaflet API. I Added a click function to our submit button, and added the Leaflet map to our site.

**Comment by Goobber33** [comment]
Markers now move when the "Submit, Next and Previous" buttons are selected. They show which businesses the user searched for
